name: fingerprint_dart_auth_sdk_dart_web_app
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  web: ^1.1.1
  fingerprint_dart_auth_sdk:
    path: ../../../fingerprint-dart-auth-sdk

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.6
  lints: ^6.0.0
