name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.3

dependencies:
  flutter:
    sdk: flutter

  fingerprint_dart_auth_sdk:
    path: ../../../fingerprint-dart-auth-sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
