name: fingerprint_dart_auth_sdk
description: A Dart SDK for Fingerprint Authentication, enabling secure server-side authentication and user management for Dart-based backend applications.
version: 0.0.3
repository: https://github.com/aortem/fingerprint-dart-auth-sdk
license: BSD-3

environment:
  sdk: ^3.10.3

# Add regular dependencies here.

dependencies:
#------------------ STANDARD FEATURES----------------------dart-----------
## There are three standard libraries.  Each one can be used with a different xxx 

  ds_standard_features: ^0.1.5
  build_web_compilers: ^4.3.0
  jwt_generator: ^0.0.8
  


#------------------ TESTING FEATURES---------------------------------

dev_dependencies:
  ds_tools_testing: ^0.1.4
  git_hooks: any
  lints: any

# Optional Local Hooks for development.
git_hooks:
  hooks:
    pre-commit: ./local_dev_tools/validate_commit.dart
    commit-msg: ./local_dev_tools/validate_commit_msg.dart
    pre-push: ./local_dev_tools/validate_branch.dart
